### ISSUE TITLE
[BUG] Failure to Update

### ISSUE THREAD

**Issue by RobertBColton** [msys2/MSYS2-packages#2033]
Azure and AppVeyor builds started doing this just a few hours ago.

```
:: Synchronizing package databases...
downloading mingw32.db...
downloading mingw32.db.sig...
error: mingw32: key "(REDACTED)" is unknown
error: mingw32: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: failed to update mingw32 (invalid or corrupted database (PGP signature))
:: Import PGP key (REDACTED) "David Macek <david.macek.0@gmail.com>", created: 2018-01-14? [Y/n] 
downloading mingw64.db...
downloading mingw64.db.sig...
error: mingw64: signature from "David Macek <(REDACTED)>" is unknown trust
error: failed to update mingw64 (invalid or corrupted database (PGP signature))
downloading msys.db...
downloading msys.db.sig...
error: msys: signature from "David Macek <(REDACTED)>" is unknown trust
error: failed to update msys (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
##[error]Cmd.exe exited with code '1'.
Finishing: Update MSYS2
```

**Comment by DDoSolitary** [comment]
Same here.

**Comment by adonaimartins** [comment]
same here

**Comment by drencorxeen** [comment]
same here as well

**Comment by lazka** [comment]
We've reverted some things. Can anyone try again?

**Comment by Biswa96** [comment]
Some packages were updated one minute ago now those are downgrading. No signature issue in my case.

**Comment by lazka** [comment]
> Some packages were updated one minute ago now those are downgrading. No signature issue in my case.

that's expected

**Comment by c72578** [comment]
@lazka OK, it is working now again. The signature issue reported here has disappeared.
Would you mind posting a link here to what was reverted (what fixed it)?

**Comment by Biswa96** [comment]
Nothing is fixed. Just revereted yesterday's change. Join Gitter chat for further information.

**Comment by elieux** [comment]
The pacman database files (http://repo.msys2.org/msys/x86_64/msys.db and others).

**Comment by cgille** [comment]
First of all, many thanks for this useful software.

I also have a problem updating.

I closed all msys2 und stopped the sshd service.
on the Windows Server 2016.
When I use msys2-x86_64-20200629.exe for msys2 installation, I cannot start a shell
C:\msys64\usr\bin\bash at cmd.exe shell gave a message like
bash shared_info::initialize: size of shared memory region changed from xxx to xxx
Sorry for not keeping the exact message.
I repeated the process twice with the same result.
Installing with older version msys2-x86_64-20190524.exe works fine.
However,  pacman -Sy msys2-runtimerenders the Msys2 unfunctional again.
I am currently happy with the msys2-x86_64-20190524.exe installation.

**Comment by marawuti** [comment]
Just attempted pacman -Su and hit this snag. Found this thread and was still unable to find actions I can take to recover.

Is there a simple set of actions to take advantage of the reverted elements? Do I need to reinstall a particular version then update?

**Comment by Biswa96** [comment]
This instruction may help https://www.msys2.org/news/#2020-06-29-new-packagers.

**Comment by marawuti** [comment]
Thank you

**Comment by jeremyd2019** [comment]
```
curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
```

I noticed that these are not present in the i686 directory.  I am running on a 32-bit OS, and never got these updates through normal ```pacman -Syuu```.  Should they have been in i686 as well as x86_64, even though they are -any?  I installed manually as per the instructions in the link, and that worked, but wants to downgrade msys2-keyring back to -r9...

**Comment by lazka** [comment]
> I noticed that these are not present in the i686 directory.

See https://www.msys2.org/news/#2020-05-17-32-bit-msys2-no-longer-actively-supported

**Comment by jeremyd2019** [comment]
Oh dear. I have a tablet with a 32-bit UEFI and cannot boot a 64-bit Windows despite having a 64-bit capable processor.

**Comment by ukai** [comment]
signature issues happens again?

```
>pacman -Sy --noconfirm 
error: mingw32: signature from "David Macek <david.macek.0@gmail.com>" is marginal trust
error: mingw64: signature from "David Macek <david.macek.0@gmail.com>" is marginal trust
error: msys: signature from "David Macek <david.macek.0@gmail.com>" is marginal trust
:: Synchronizing package databases...
downloading mingw32.db...
downloading mingw32.db.sig...
error: mingw32: signature from "David Macek <david.macek.0@gmail.com>" is marginal trust
error: failed to update mingw32 (invalid or corrupted database (PGP signature))
downloading mingw64.db...
downloading mingw64.db.sig...
error: mingw64: signature from "David Macek <david.macek.0@gmail.com>" is marginal trust
error: failed to update mingw64 (invalid or corrupted database (PGP signature))
downloading msys.db...
downloading msys.db.sig...
error: msys: signature from "David Macek <david.macek.0@gmail.com>" is marginal trust
error: failed to update msys (invalid or corrupted database (PGP signature))
error: failed to synchronize any databases
error: failed to init transaction (invalid or corrupted database (PGP signature))
```

**Comment by lazka** [comment]
yes, see #2058

**Comment by Juan321654** [comment]
still happening
